[alias]
scaffold = "run --release -- scaffold"
download = "run --release -- download"
read = "run --release -- read"

solve = "run --release -- solve"
all = "run --release -- all"
time = "run --release -- all --release --time"

[env]
AOC_YEAR = "2023"
